const j = async (res) => {
  if (!res.ok) throw new Error((await res.json().catch(() => ({}))).error || res.statusText)
  return res.json()
}
const H = { 'Content-Type': 'application/json' }
export const getState = () => fetch('/api/state').then(j)
export const createTask = (body) => fetch('/api/tasks', { method: 'POST', headers: H, body: JSON.stringify(body) }).then(j)
export const patchTask = (id, body) => fetch(`/api/tasks/${id}`, { method: 'PATCH', headers: H, body: JSON.stringify(body) }).then(j)
export const removeTask = (id) => fetch(`/api/tasks/${id}`, { method: 'DELETE' }).then(j)
export const sync = () => fetch('/api/sync', { method: 'POST' }).then(j)
export const syncSource = (key) => fetch(`/api/sync/${key}`, { method: 'POST' }).then(j)
export const signInSource = (key) => fetch(`/api/sources/${key}/signin`, { method: 'POST' }).then(j)
export const signIn = (tier = 'core') => fetch('/api/auth/signin', { method: 'POST', headers: H, body: JSON.stringify({ tier }) }).then(j)
export const signOut = () => fetch('/api/auth/signout', { method: 'POST' }).then(j)
/** Opens in the system browser under Electron, a new tab otherwise. */
export const openExternal = (url) => window.bench?.openExternal ? window.bench.openExternal(url) : window.open(url, '_blank', 'noopener')
export const getTimeclock = () => fetch('/api/timeclock').then(j)
export const punch = (kind) => fetch('/api/timeclock/punch', { method: 'POST', headers: H, body: JSON.stringify({ kind }) }).then(j)
export const resetTimeclock = () => fetch('/api/timeclock/reset', { method: 'POST' }).then(j)
export const getSettings = () => fetch('/api/settings').then(j)
export const saveSettings = (patch) => fetch('/api/settings', { method: 'PUT', headers: H, body: JSON.stringify(patch) }).then(j)
/** A tom.fit tool in its own signed-in window under Electron; a tab otherwise. */
export const openTool = (url) => window.bench?.openTool ? window.bench.openTool(url) : window.open(url, '_blank', 'noopener')
export const getLogbook = () => fetch('/api/logbook').then(j)
export const createEntry = (body) => fetch('/api/logbook', { method: 'POST', headers: H, body: JSON.stringify(body) }).then(j)
export const patchEntry = (id, body) => fetch(`/api/logbook/${id}`, { method: 'PATCH', headers: H, body: JSON.stringify(body) }).then(j)
export const removeEntry = (id) => fetch(`/api/logbook/${id}`, { method: 'DELETE' }).then(j)
export const actionToBoard = (id, aid) => fetch(`/api/logbook/${id}/actions/${aid}/to-board`, { method: 'POST' }).then(j)
export const getMaps = () => fetch('/api/napkin').then(j)
export const createMap = (body) => fetch('/api/napkin', { method: 'POST', headers: H, body: JSON.stringify(body) }).then(j)
export const patchMap = (id, body) => fetch(`/api/napkin/${id}`, { method: 'PATCH', headers: H, body: JSON.stringify(body) }).then(j)
export const removeMap = (id) => fetch(`/api/napkin/${id}`, { method: 'DELETE' }).then(j)
export const todaysMeetings = () => fetch('/api/calendar/today').then(j)
export const getWeek = () => fetch('/api/week').then(j)
